<a href="https://colab.research.google.com/github/Jesica3018/APMKelompok6/blob/main/TB_GaussianNaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing the libraries  

import numpy as np 
import pandas as pd  

In [ ]:
# Importing the data
dataset= pd.read_csv('processed-anggaran-jakarta-belanja-langsung-per-kegiatan.csv')  
x = dataset.iloc[:, [1, 5, 7]].values  
y = dataset.iloc[:, 0].values  

In [ ]:
#taking a look at the data

dataset.head()

komisi  skpdid kode_skpd              belanja         nama_skpd  \
0       1       4  1.20.002  Belanja Barang Jasa  SEKRETARIAT DPRD   
1       1       4  1.20.002      Belanja Pegawai  SEKRETARIAT DPRD   
2       1       4  1.20.002  Belanja Barang Jasa  SEKRETARIAT DPRD   
3       1       4  1.20.002      Belanja Pegawai  SEKRETARIAT DPRD   
4       1       4  1.20.002  Belanja Barang Jasa  SEKRETARIAT DPRD   

   id_kegiatan                                           kegiatan  \
0        33450  Fasilitasi Laporan Pajak Monev DPRD dan Sekret...   
1        38412  Konfirmasi Realisasi Anggaran dengan SKPD terkait   
2        38412  Konfirmasi Realisasi Anggaran dengan SKPD terkait   
3        38431            Penyusunan Neraca, LRA, dan CALK, LAKIP   
4        38444  Fasilitasi Kegiatan Penatausahaan dan Pengelol...   

   nilai_anggaran  
0     251400000.0  
1     152760000.0  
2        600000.0  
3     220000000.0  
4     252050000.0

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85673 entries, 0 to 85672
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   komisi          85673 non-null  int64  
 1   skpdid          85673 non-null  int64  
 2   kode_skpd       85673 non-null  object 
 3   belanja         85673 non-null  object 
 4   nama_skpd       85673 non-null  object 
 5   id_kegiatan     85673 non-null  int64  
 6   kegiatan        85673 non-null  object 
 7   nilai_anggaran  85673 non-null  float64
dtypes: float64(1), int64(3), object(4)
memory usage: 5.2+ MB


In [ ]:
#splitting the data into training and testing sets

from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 5)

In [ ]:
# Feature Scaling  

from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
X_train = sc.fit_transform(x_train)  
X_test = sc.transform(x_test) 

In [ ]:
# Fitting Naive Bayes to the Training set  

from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

GaussianNB()

In [ ]:
# Predicting the Test set results  

y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [ ]:
#Confusion Matrix  

from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)  

print(cm) 

[[10636     1   105    49    27]
 [ 2270     8   224   135    13]
 [  416     2   177    16     4]
 [ 2543    11    88   110    61]
 [ 3942     6   140   383    52]]


In [ ]:
#Accuracy score

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred) 

0.5127690368364536

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.54      0.98      0.69     10818
           2       0.29      0.00      0.01      2650
           3       0.24      0.29      0.26       615
           4       0.16      0.04      0.06      2813
           5       0.33      0.01      0.02      4523

    accuracy                           0.51     21419
   macro avg       0.31      0.26      0.21     21419
weighted avg       0.40      0.51      0.37     21419

